### ISSUE TITLE
Add function to sales used part

### ISSUE THREAD

**Issue by MohammedMustafaHAssan** [MohammedMustafaHAssan/SQA18F18333#1]

**Comment by SayedhassanUddin** [comment]
public void sellUsedItem(String item, int quantity, int condition) {
  int currentQuantity = inventory.get(item);
  if (currentQuantity < quantity) {
    System.out.println("Sorry, we do not have enough of that item in stock.");
    return;
  }
  inventory.put(item, currentQuantity - quantity);
  int price = prices.get(item);
  int discountedPrice = (int)(price * (100 - condition) / 100.0);
  int totalPrice = discountedPrice * quantity;
  System.out.println("Selling " + quantity + " " + item + " (used, condition " + condition + "%) for a total of $" + totalPrice);
}
